### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TheSamadAzeez**
Update on the README for a better understanding of when making changes to the repo, feel free to add more detailed description for better usage

### CODE REVIEW

**Comment by okondev2021** [comment]
definitely, forgot about it. Concerning the header it should be CGPA Calculator without the component since it's an app. The component structure is solid, i don't think there's any need for the usage.

**Comment by okondev2021** [comment]
Also the license you added

**Comment by okondev2021** [comment]
Feel free to customize this README to better fit your project's specifics, such as adding more detailed installation instructions, contributing guidelines, or expanding the usage section with additional examples??

**Comment by okondev2021** [comment]
@Samad-Azeez Review the second commit made on the PR.

**Review by TheSamadAzeez — COMMENTED** [review]
Ok, that's good
Let's go with this

**Review by TheSamadAzeez — COMMENTED** [review]
You can proceed with merging

**Pull request merged**
